"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";

import styles from "./Hero.module.scss";
import TrustBadge from "@/components/features/trust-badge/TrustBadge";
import SelfBuildingPlan, { PanelData } from "@/components/features/self-building-plan/SelfBuildingPlan";
import MagneticButton from "@/components/ui/magnetic-button/MagneticButton";

interface HeroSectionProps {
    title: string;
    highlight?: string;
    description: string;
    primaryCta?: { text: string; link: string };
    secondaryCta?: { text: string; link: string };
    image?: string;
    align?: "left" | "right";
    showTrustBadge?: boolean;
    /** Two-item rotator shown in the eyebrow pill. Defaults to the homepage duality. */
    eyebrowRotator?: string[];
    /** Content for the right-side self-building document panel. */
    panel?: PanelData;
}

const DEFAULT_ROTATE = ["Written by Experts", "Generated by AI"];

const HeroSection: React.FC<HeroSectionProps> = ({
    title,
    highlight,
    description,
    primaryCta,
    secondaryCta,
    showTrustBadge = false,
    eyebrowRotator,
    panel,
}) => {
    const reduce = useReducedMotion();
    const rotate =
        eyebrowRotator && eyebrowRotator.length > 0 ? eyebrowRotator : DEFAULT_ROTATE;
    const [rotateIdx, setRotateIdx] = useState(0);

    useEffect(() => {
        if (reduce || rotate.length <= 1) return;
        const id = setInterval(() => {
            setRotateIdx((i) => (i + 1) % rotate.length);
        }, 2600);
        return () => clearInterval(id);
    }, [reduce, rotate.length]);

    const words = title.split(" ");
    const currentLabel = rotate[rotateIdx % rotate.length];

    return (
        <section className={styles.hero}>
            {/* Aurora background */}
            <div className={styles.aurora} aria-hidden="true">
                <div className={styles.blob1} />
                <div className={styles.blob2} />
                <div className={styles.blob3} />
                <div className={styles.grid} />
                <div className={styles.noise} />
            </div>

            <div className={styles.inner}>
                <div className={styles.content}>
                    <motion.div
                        className={styles.eyebrow}
                        initial={{ opacity: 0, y: 8 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                    >
                        <span className={styles.eyebrowDot} />
                        <AnimatePresence mode="wait">
                            <motion.span
                                key={currentLabel}
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -10 }}
                                transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
                            >
                                {currentLabel}
                            </motion.span>
                        </AnimatePresence>
                    </motion.div>

                    <h1 className={styles.title}>
                        {words.map((w, i) => (
                            <motion.span
                                key={`${w}-${i}`}
                                className={styles.word}
                                initial={{ opacity: 0, y: 24 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{
                                    duration: 0.55,
                                    ease: [0.16, 1, 0.3, 1],
                                    delay: 0.05 + i * 0.045,
                                }}
                            >
                                {w}
                            </motion.span>
                        ))}
                    </h1>

                    {highlight && (
                        <motion.p
                            className={styles.highlight}
                            initial={{ opacity: 0, y: 16 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.35, ease: [0.16, 1, 0.3, 1] }}
                        >
                            {highlight}
                        </motion.p>
                    )}

                    <motion.p
                        className={styles.desc}
                        initial={{ opacity: 0, y: 16 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6, delay: 0.5, ease: [0.16, 1, 0.3, 1] }}
                    >
                        {description}
                    </motion.p>

                    <motion.div
                        className={styles.actions}
                        initial={{ opacity: 0, y: 12 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6, delay: 0.65, ease: [0.16, 1, 0.3, 1] }}
                    >
                        {primaryCta && (
                            <MagneticButton as="a" href={primaryCta.link} className={styles.primaryCta}>
                                <Link href={primaryCta.link} className={styles.primaryCtaInner}>
                                    <span>{primaryCta.text}</span>
                                    <span className={styles.ctaArrow} aria-hidden>→</span>
                                </Link>
                            </MagneticButton>
                        )}
                        {secondaryCta && (
                            <Link href={secondaryCta.link} className={styles.secondaryCta}>
                                <span>{secondaryCta.text}</span>
                                <span className={styles.ctaArrow} aria-hidden>→</span>
                            </Link>
                        )}
                    </motion.div>

                    {showTrustBadge && (
                        <motion.div
                            initial={{ opacity: 0, y: 12 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.85, ease: [0.16, 1, 0.3, 1] }}
                            className={styles.trust}
                        >
                            <TrustBadge />
                        </motion.div>
                    )}
                </div>

                <div className={styles.centerpiece}>
                    <SelfBuildingPlan panel={panel} />
                </div>
            </div>
        </section>
    );
};

export default HeroSection;
